apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bases/vault.infra.doodle.com_vaultbindings.yaml
- bases/vault.infra.doodle.com_vaultmirrors.yaml
# +kubebuilder:scaffold:crdkustomizeresource
