
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - infra.doodle.com
  resources:
  - VaultBindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infra.doodle.com
  resources:
  - VaultBindings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - infra.doodle.com
  resources:
  - VaultMirrors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infra.doodle.com
  resources:
  - VaultMirrors/status
  verbs:
  - get
  - patch
  - update
