---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vault.infra.doodle.com
  resources:
  - vaultbindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vault.infra.doodle.com
  resources:
  - vaultbindings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - vault.infra.doodle.com
  resources:
  - vaultmirrors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vault.infra.doodle.com
  resources:
  - vaultmirrors/status
  verbs:
  - get
  - patch
  - update
