# permissions for end users to edit mongodbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vaultbinding-editor-role
rules:
- apiGroups:
  - vault.infra.doodle.com
  resources:
  - vaultbindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vault.infra.doodle.com
  resources:
  - vaultbindings/status
  verbs:
  - get
