# permissions for end users to view mongodbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vaultbinding-viewer-role
rules:
- apiGroups:
  - vault.infra.doodle.com
  resources:
  - vaultbindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vault.infra.doodle.com
  resources:
  - vaultbindings/status
  verbs:
  - get
