{{- if .Values.clusterRBAC.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "k8svault-controller.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "k8svault-controller.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "k8svault-controller.chart" . }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
rules:
- apiGroups: ['v1']
  resources:
    - "secrets"
  verbs:
    - get
    - list
    - watch
- apiGroups:
  - ""
  resources:
  - VaultBindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - VaultBindings/status
  verbs:
  - get
  - patch
  - update
{{- end }}
