name: Release Chart

on:
  push:
    branches:
      - master
      - DK-2819

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.3.0
        with:
          charts_dir: ./chart
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Publish Helm chart
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          charts_dir: ./chart
          charts_url: https://doodlescheduling.github.io/charts
          owner: DoodleScheduling
          repository: charts
          branch: gh-pages
          #commit_username: johndoe
          #commit_email: johndoe@example.com
